### PR TITLE
Email a friend

### PR DESCRIPTION
**Pull request by racoonbest**
@racoonbest Can you please approve my pull request?

### CODE REVIEW

**Comment by racoonbest** [comment]
Please fix the assertion. Other than that minor issue I don't see anything that will stop from merging

**Comment by kseo08** [comment]
@racoonbest @Tony4kor Last step for verifying the message section is updated; Assert is modified.
Please confirm and approve the merge pull request. Thanks!

**Comment by racoonbest** [comment]
@kseo08 Rework your automation with POM

**Comment by racoonbest** [comment]
Hi @imomali7 
Please help @kseo08 to make this branch ready to merge to main by updating her EmailAFrined.java class by converting into POM.
Thank you for your help in advance!

**Comment by imomali7** [comment]
@racoonbest the code is ready but when I pushed it has conflict in GitHub

**Comment by imomali7** [comment]
Code Conflict solved Ready to Merge @racoonbest

**Comment by racoonbest** [comment]
This branch has broken code. @kseo08 's newer branch should fix this existing one once she merges to main
@imomali7 thank you!

**Pull request merged**
